apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fintech-postgres-pvc-efs
  namespace: fintech
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
