apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-frontend
  namespace: fintech
  labels:
    app: fintech-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintech-frontend
  template:
    metadata:
      labels:
        app: fintech-frontend
    spec:
      containers:
        - name: frontend
          image: sof777/unir:frontend-v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: fintech-frontend-config
                  key: REACT_APP_API_URL
         # resources:
         #   requests:
         #     cpu: "100m"
         #     memory: "128Mi"
         #   limits:
         #     cpu: "300m"
         #     memory: "256Mi"
---
# Despliegue del frontend. Reemplazar la imagen con la versión de producción construida.
